site_name: 我的文档
nav:

  - 首页: index.md
  - 技术文案: 
        - 智慧水务建设: 技术文案/智慧水务建设.md
        - 能耗管理系统: 技术文案/能耗管理系统.md
        - 其他: 技术文案/others.md
  - 开发人员指南:
        - API 参考: developer/api.md
        - 部署指南: developer/deployment.md
  - 关于: 
        - 项目简介: about/project.md
        - 联系我们: about/contact.md


theme:
    name: material
    features:
       - navigation.tabs
       - toc.integrate
       - navigation.expand
       - navigation.sections
       - navigation.instant
       
